/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewGoalRouteImport } from './routes/new-goal'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanGoalIdRouteImport } from './routes/plan.$goalId'

const NewGoalRoute = NewGoalRouteImport.update({
  id: '/new-goal',
  path: '/new-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanGoalIdRoute = PlanGoalIdRouteImport.update({
  id: '/plan/$goalId',
  path: '/plan/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/new-goal': typeof NewGoalRoute
  '/plan/$goalId': typeof PlanGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/new-goal': typeof NewGoalRoute
  '/plan/$goalId': typeof PlanGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/new-goal': typeof NewGoalRoute
  '/plan/$goalId': typeof PlanGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goals' | '/new-goal' | '/plan/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goals' | '/new-goal' | '/plan/$goalId'
  id: '__root__' | '/' | '/goals' | '/new-goal' | '/plan/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsRoute: typeof GoalsRoute
  NewGoalRoute: typeof NewGoalRoute
  PlanGoalIdRoute: typeof PlanGoalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-goal': {
      id: '/new-goal'
      path: '/new-goal'
      fullPath: '/new-goal'
      preLoaderRoute: typeof NewGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$goalId': {
      id: '/plan/$goalId'
      path: '/plan/$goalId'
      fullPath: '/plan/$goalId'
      preLoaderRoute: typeof PlanGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsRoute: GoalsRoute,
  NewGoalRoute: NewGoalRoute,
  PlanGoalIdRoute: PlanGoalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
